version: "3"

volumes:
  postgres_data:
  pgadmin:

services:
  mega_market:
    container_name: mega_market
    build: .
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
