version: "3"

volumes:
  postgres_data:

services:
  mega_market:
    restart: always
    container_name: mega_market
    build: .
    expose:
      - 80
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    restart: always
    container_name: postgres_container
    image: postgres:latest
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    restart: always
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - mega_market
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
